version: '3'
services:
  libraryweb:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/librarycode/
    ports:
      - "8000:8000"
    depends_on:
      - librarydb
  librarydb:
    image: postgres
    ports:
      - "5432:5432"